ErrorException: fclose() expects parameter 1 to be resource, null given
Trace

/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php:4122
/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php:3167
/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php:3157
/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php:3173